<?php

declare(strict_types=1);

namespace Cardlink\Checkout\Service;

use Cardlink\Checkout\Model\ApiFields;
use Magento\Framework\Exception\LocalizedException;
use Magento\Sales\Model\Order\Payment\Transaction;

/**
 * Builds and resolves the "orderid" value exchanged with the Cardlink payment gateway.
 *
 * The gateway identifies a transaction solely by the orderid sent with the original
 * payment request, and every secondary transaction (capture/refund/void/status) has to
 * echo that exact value back. It is never the plain Magento increment ID, because a
 * random suffix is always appended so the same order can be paid for more than once:
 *
 *  - "Create order and hold stock" = Yes -> "{incrementId}x{suffix}"
 *  - "Create order and hold stock" = No  -> "QUOTEx{quoteId}x{suffix}"
 *
 * In the second flow the Magento order does not exist yet when the payment request is
 * built, so the quote ID is sent instead and the order is created once the gateway
 * confirms the payment. Sending the resulting increment ID to the XML API therefore
 * fails with "Original transaction is not found" (error code O2).
 *
 * @author Cardlink S.A.
 */
class GatewayOrderId
{
    /**
     * Prefix marking an orderid that encodes a quote instead of an order.
     */
    const QUOTE_PREFIX = 'QUOTEx';

    /**
     * Build the entity part of the gateway orderid for a quote.
     *
     * The random suffix is appended afterwards, by the common form data builder.
     *
     * @param int|string $quoteId
     * @return string
     */
    public function forQuote($quoteId): string
    {
        return self::QUOTE_PREFIX . $quoteId;
    }

    /**
     * Resolve the Magento entity a gateway orderid refers to.
     *
     * Both keys can be populated: callers are expected to look the order up first and
     * fall back to the quote, which is what keeps orderids generated by older versions
     * of this module (an unprefixed quote ID) working.
     *
     * @param string $gatewayOrderId The orderid as sent to / received from the gateway.
     * @return array{quote_id: int|null, increment_id: string}
     */
    public function parse(string $gatewayOrderId): array
    {
        $gatewayOrderId = trim($gatewayOrderId);

        if ($gatewayOrderId === '') {
            return ['quote_id' => null, 'increment_id' => ''];
        }

        if (strpos($gatewayOrderId, self::QUOTE_PREFIX) === 0) {
            // "QUOTEx{quoteId}x{suffix}" - the quote ID is the second "x"-separated part.
            // Splitting instead of trimming the suffix also covers the orderids produced
            // by the builds that appended the random suffix twice.
            $parts = explode('x', $gatewayOrderId);
            $quoteId = isset($parts[1]) && ctype_digit($parts[1]) ? (int) $parts[1] : null;

            // There is no order to look up yet: it is created after payment is confirmed.
            return ['quote_id' => $quoteId, 'increment_id' => ''];
        }

        $incrementId = $this->stripSuffix($gatewayOrderId);

        return [
            // Before the "QUOTEx" prefix existed the quote flow sent a bare quote ID.
            'quote_id' => ctype_digit($incrementId) ? (int) $incrementId : null,
            'increment_id' => $incrementId,
        ];
    }

    /**
     * Remove the random suffix appended when the payment request was built.
     *
     * @param string $gatewayOrderId
     * @return string
     */
    public function stripSuffix(string $gatewayOrderId): string
    {
        $length = strlen($gatewayOrderId) - ApiFields::OrderId_SuffixLength;

        return $length > 0 ? substr($gatewayOrderId, 0, $length) : $gatewayOrderId;
    }

    /**
     * Retrieve the orderid the gateway knows this payment by.
     *
     * @param \Magento\Payment\Model\InfoInterface|\Magento\Sales\Model\Order\Payment $payment
     * @return string|null Null when the payment carries no gateway orderid at all.
     */
    public function resolveForPayment($payment): ?string
    {
        $orderId = trim((string) $payment->getData('cardlink_order_id'));

        if ($orderId !== '') {
            return $orderId;
        }

        // Orders placed before cardlink_order_id existed - and installations upgraded
        // from a version whose InstallSchema had not added the column yet - still carry
        // the gateway orderid in the raw details recorded with the payment transaction.
        $additionalInformation = $payment->getAdditionalInformation();

        if (is_array($additionalInformation)
            && isset($additionalInformation[Transaction::RAW_DETAILS][ApiFields::OrderId])
        ) {
            $orderId = trim((string) $additionalInformation[Transaction::RAW_DETAILS][ApiFields::OrderId]);

            if ($orderId !== '') {
                return $orderId;
            }
        }

        return null;
    }

    /**
     * Retrieve the orderid the gateway knows this payment by, or fail loudly.
     *
     * The Magento increment ID is deliberately not used as a fallback: the gateway
     * orderid always carries a random suffix (and, in the quote flow, a quote ID rather
     * than an order number), so sending the increment ID can only ever come back as
     * "Original transaction is not found". Reporting the missing reference is clearer.
     *
     * @param \Magento\Payment\Model\InfoInterface|\Magento\Sales\Model\Order\Payment $payment
     * @param string $operation Operation name used in the error message.
     * @return string
     * @throws LocalizedException
     */
    public function requireForPayment($payment, string $operation): string
    {
        $orderId = $this->resolveForPayment($payment);

        if ($orderId !== null) {
            return $orderId;
        }

        throw new LocalizedException(
            __(
                'The Cardlink transaction reference for this order is missing, so the %1 cannot be'
                    . ' sent to the payment gateway. Please run "bin/magento setup:upgrade" to add the'
                    . ' cardlink_order_id column, and handle this order from the Cardlink merchant portal.',
                $operation
            )
        );
    }
}
